local root = vim.fn.fnamemodify(debug.getinfo(1, "S").source:sub(2), ":p:h:h")
vim.opt.runtimepath:prepend(root)

local events = {}
local errors = {}
local decoder = require("paj.protocol").decoder(function(event)
  table.insert(events, event)
end, function(err)
  table.insert(errors, err)
end)
decoder.feed({ '{"event":"accepted",' })
decoder.feed({ '"id":"one"}', "" })
decoder.feed({ '{"event":"delta","text":"hel"}', '{"event":"complete","text":"hello"}' })
decoder.finish()
assert(#errors == 0)
assert(#events == 3)
assert(events[2].text == "hel")
assert(events[3].event == "complete")

vim.api.nvim_buf_set_name(0, "/tmp/example.lua")
vim.api.nvim_buf_set_lines(0, 0, -1, false, { "local one = 1", "return one" })
vim.api.nvim_win_set_cursor(0, { 2, 0 })
local context = require("paj.context")
local explanation = context.explain({ args = "values", range = 0, line1 = 2, line2 = 2 })
assert(explanation:find('path="/tmp/example.lua"', 1, true))
assert(explanation:find("return one", 1, true))
assert(not explanation:find("local one", 1, true))
local review = context.review({ args = "", range = 0, line1 = 1, line2 = 1 })
assert(review:find("local one", 1, true))
assert(review:find("return one", 1, true))

require("paj").setup()
assert(vim.fn.exists(":PajSessions") == 2)
assert(vim.fn.exists(":PajPrompt") == 2)
assert(vim.fn.exists(":PajExplain") == 2)
assert(vim.fn.exists(":PajReview") == 2)

print("paj.nvim headless tests passed")
vim.cmd("qa!")
